version: '3'

services:

  Serialize:
    image: php:7-apache
    restart: always
    ports:
      - 10001:80
    volumes:
      - ./Serialize/src:/var/www/html:ro
      - ./Serialize/flag:/flag_962025850113.txt:ro

  Manager:
    image: php:7-apache
    restart: always
    ports:
      - 10002:80
    volumes:
      - ./Manager/src:/var/www/html:ro
      - ./Manager/src/upload:/var/www/html/upload
      - ./Manager/flag:/flag_215490273139.txt:ro

  SSGo:
    image: tiangolo/uwsgi-nginx-flask:python3.8
    restart: always
    ports:
      - 10003:80
    volumes:
      - ./SSGo/src:/app:ro
      - ./SSGo/flag:/flag_354089518978.txt:ro
