version: '3'

services:

  Serialize:
    image: php:7-apache
    restart: always
    ports:
      - 10001:80
    volumes:
      - ./Serialize/html:/var/www/html:ro
      - ./Serialize/flag:/flag_962025850113.txt
